### ISSUE TITLE
Slow tests

### ISSUE THREAD

**Issue by dundalek** [dundalek/closh#11]
The whole test suite takes minutes to run, which is too slow. The reason for this is that it spawns child process to evaluate each closh case.

Possible solutions:
1) Make the [test runner](https://github.com/bensu/doo) run on Lumo, that way we could evaluate the test cases within the test runner process.
2) Start one evaluator process, then use some sort of IPC to send code to evaluate and results back to test runner process.

**Comment by mnewt** [comment]
@dundalek What's the reason the tests are running under doo? I'm trying to remove it and make a thin lumo wrapper to run from there. So far it looks workable, I'm just having to re-plumb a few things. Not sure if I'll run into a roadblock but nothing yet.

**Comment by dundalek** [comment]
@mnewt Doo is the default runner in the template I used. If we can switch to lumo directly that would be great.

**Comment by mnewt** [comment]
Please see #25
