### ISSUE TITLE
BUG: Rebel arity error when set as default tmux shell

### ISSUE THREAD

**Issue by jaidetree** [dundalek/closh#114]
# REPRODUCTION
1. Run a working tmux instance
2. Modify and run the following command through tmux (ctrl-b+:)
    `set -g default-shell /path/to/closh-zero.jar`
3. Create a new tmux window (ctrl-b+c)

## EXPECTED
A new closh shell is created running the jar

## ACTUAL
An error message flashes and the window closes. 

![screen shot 2018-12-11 at 2 49 16 pm](https://user-images.githubusercontent.com/590297/49826777-c55c2d00-fd55-11e8-8356-ac5acaaa7669.png)

### Notes:
  - Was able to get the error message via screen recording then taking a screenshot.

## ENVIRONMENT

| Name              | Value                    |
| ----------------- | ------------------------ |
| Operating System: | OS X Mojave (10.14)      |
| TMUX version:     | 2.8                      |
| Original shell:   | zsh                      |
| Java Version:     | java version "1.8.0_144" |

Let me know if any other information would be helpful. This is an awesome project and I would love to make it my default shell :metal:

**Comment by dundalek** [comment]
Thank you, what a superb bug report :ok_hand:

I think I have a clue where the issue might be, will look into it.

**Comment by dundalek** [comment]
I just published a tiny new release with a fix which should take care of this: https://github.com/dundalek/closh/releases/tag/v0.3.2

Please let me know if it works for you.

**Comment by jaidetree** [comment]
Tested it, works just fine. Thanks!

**Comment by dundalek** [comment]
Cool :+1:
