### ISSUE TITLE
Feature: User-defined Aliases, Abbreviations, Functions and Commands

### ISSUE THREAD

**Issue by dundalek** [dundalek/closh#12]
For user defined helpers I am thinking of supporting following:

## Aliases

Aliases for defining / overriding functionality. When alias is used it does not get expanded and is saved into history as is.

Example:
```clojure
(defalias ls "ls --color=auto")
```

## Abbreviations

Abbreviations are similar to aliases but expand to underlying definition. Therefore autocomplete can work seamlessly and also full command is saved to history. Inspired by [abbr](https://fishshell.com/docs/current/commands.html#abbr) in fish. See also [discussion](https://github.com/fish-shell/fish-shell/issues/731).

```clojure
(defabbrev ga "git add")
(defabbr gaa "git add --all")
```

## Functions

Classic Clojure functions, already works.

```clojure
(defn hello [name]
  (str "Hello " name))
```

Run in command line like: `(hello "World")`.

## Commands

Similar to functions, but can be executed like commands without parens. Related to builtin commands. Defining similar to defn:

```clojure
(defcmd hello [name]
  (str "Hello " name))
```
Run in command line like: `hello World`. There should probably also be a way to promote existing function to a command.

**Comment by 4mitch** [comment]
Will it work like init.el in Emacs?

**Comment by dundalek** [comment]
@4mitch Currently we load `~/.closhrc` on startup so users will be able to put these kinds of definitions there. So you could say it is similar to Emacs init (from my limited understanding of Emacs).

**Comment by mnewt** [comment]
@dundalek Have you started on this yet? If not, I can tackle it

**Comment by dundalek** [comment]
I do work on it, I have an work in progress branch here: https://github.com/dundalek/closh/tree/feature/custom-commands-aliases

**Comment by dundalek** [comment]
This is now ready in master branch.
