### ISSUE TITLE
Parsing manual pages for auto-completion

### ISSUE THREAD

**Issue by dundalek** [dundalek/closh#13]
This is not an immediate concern but I am creating an issue for discussion and to collect currently existing approaches and maybe for someone to take a stab at it.

Parsing manual pages is a messy business since there is no single standard and there are many slight variations.

Existing approaches:
- Only project I am currently aware to attempt this is fish with [fish_update_completions](https://www.fishshell.com/docs/current/commands.html#fish_update_completions
) (source [here](https://github.com/fish-shell/fish-shell/blob/649e24409220939022c94c17d6ec90be5f5f367f/share/functions/fish_update_completions.fish)).
- Other project is [explainshell](https://github.com/idank/explainshell) but it does not handle command grammars so it is not a suitable approach (it could generate invalid suggestions).

What I imagine:
- If completion definitions for a command are not available then try to parse `man command` or `command --help` or `command -h`
- There are many variations so using a high-level parsing library like [Instaparse](https://github.com/Engelberg/instaparse) is preferred. We can define different variant of parsing rules and reuse the common rules.
- [Docopt](http://docopt.org/) seems to be most formal description of command line arguments, so it makes sense to start with parsing its format, then extend to other manual pages in the wild.

**Comment by millettjon** [comment]
Something like [compleat](https://github.com/mbrubeck/compleat) but in clojure would be useful.

**Comment by millettjon** [comment]
Could spec be used to generate completions?

**Comment by dundalek** [comment]
Compleat looks neat, but it does not have a repository of completions so I don't see much value in integrating it.

I once played with using spec to parse argument for a CLI app and I think its doable. Once you have a spec it should be possible to write a completion generator for it. It's a kind of a long shot though.

**Comment by dundalek** [comment]
Not going to be working on this anytime soon, closing for now.
