### ISSUE TITLE
Glob not properly expanding in JVM version

### ISSUE THREAD

**Issue by dundalek** [dundalek/closh#158]
Running following from withing the closh source directory does not correctly expands (in JVM versin, nodejs version works fine).
```
cd src && echo ../*.json
```

We are using clj-glob library. Maybe we could try glob implementation provided by Java using [FileSystem.getPathMatcher](https://docs.oracle.com/javase/8/docs/api/java/nio/file/FileSystem.html#getPathMatcher-java.lang.String-) in combination with [Files.walkFileTree](https://docs.oracle.com/javase/tutorial/essential/io/find.html).

Ideally I would like to see some programming language agnostic test suite, that could compare [various implementations](https://en.wikipedia.org/wiki/Glob_(programming)#Implementations). One such format could be [TAP protocol](http://testanything.org/)

There is an implementation in Julia which describes itself as POSIX spec compliant under `IEEE Std 1003.1, 2004 Edition (Open Group Base Specifications Issue 6)`: https://github.com/vtjnash/Glob.jl

More resources:
http://man7.org/linux/man-pages/man3/glob.3.html
http://man7.org/linux/man-pages/man7/glob.7.html

**Comment by kirillsalykin** [comment]
@dundalek I've opened PR to address this issue https://github.com/dundalek/closh/pull/164.

Please review.

Some tests are still failing locally, looking into this.
