### ISSUE TITLE
Cannot start with npm

### ISSUE THREAD

**Issue by loboyd** [dundalek/closh#24]
Hi. I'm new to open source contributing and git, so sorry in advance for any silly misunderstandings.
I am not able to start Closh with npm. I have cloned both from my own fork and from the original repo with the same results. When using `npm install`, I get the following  #message:

`> deasync@0.1.10 install /home/logan/Documents/closh/node_modules/deasync
> node ./build.js

`linux-x64-node-6` exists; testing
Binary is fine; exiting
npm notice created a lockfile as package-lock.json. You should commit this file.
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@1.1.2 (node_modules/fsevents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@1.1.2: wanted {"os":"darwin","arch":"any"} (current: {"os":"linux","arch":"x64"})`

and when using `npm start`, I get this message:

`> closh@0.1.3 start /home/logan/Documents/closh
> node ./bin/closh.js

events.js:160
      throw er; // Unhandled 'error' event
      ^

Error: spawn lumo ENOENT
    at exports._errnoException (util.js:949:11)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:182:32)
    at onErrorNT (internal/child_process.js:348:16)
    at _combinedTickCallback (internal/process/next_tick.js:74:11)
    at process._tickCallback (internal/process/next_tick.js:98:9)
    at Function.Module.runMain (module.js:577:11)
    at startup (node.js:160:18)
    at node.js:445:3
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! closh@0.1.3 start: `node ./bin/closh.js`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the closh@0.1.3 start script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/logan/.npm/_logs/2017-11-09T02_35_58_352Z-debug.log`

version of npm: `5.5.1`
version of node: `v6.1.0`

Any idea where I'm going wrong here? Thank you!

P.S. I can't seem to figure out the formatting. If somebody wouldn't mind helping me out there as well, that would be very much appreciated.

**Comment by dundalek** [comment]
Hi, it needs lumo. So if you run `npm install -g lumo-cljs` that should fix it for you. I will update the instructions to make it more clear.

**Comment by loboyd** [comment]
Awesome. Thank you!
