### ISSUE TITLE
History file is not created

### ISSUE THREAD

**Issue by neominik** [dundalek/closh#48]
For me the `~/.closh/closh.sqlite` file for the history is not created. There is neither a folder nor the file during or after execution of closh.
No error is printed either. It just doesn't happen.

Tested on macOS and Arch Linux. Installed via `nmp install -g lumo-cljs closh`

Any suggestions on how to debug this?

**Comment by mnewt** [comment]
The history feature isn't in the `0.1.3` release. To get it right now, you need to run from source:
```
git clone https://github.com/dundalek/closh.git
cd closh
npm start
```

I'm not sure when @dundalek is thinking of pushing another release to npm but there are a lot of features in development right now so it might be a little while.

**Comment by dundalek** [comment]
You can also install the version from master with `npm install -g lumo-cljs dundalek/closh`. I would like to push a new release soon, remaining features I need to complete are #12 and #42.

I also added changelog section in README which should indicate better which features are not yet released.

**Comment by neominik** [comment]
Okay I will close this issue since I was obviously using the wrong version.
Building from source as well as running the development version do however not work for me at the moment.
