### ISSUE TITLE
Absolute path to lumo source prevents successful build

### ISSUE THREAD

**Issue by neominik** [dundalek/closh#50]
https://github.com/dundalek/closh/blob/86969085e44157b216cb821acd6de501a2c86039/project.clj#L48

Isn't there a way to have lumo as a regular dependency?

**Comment by dundalek** [comment]
I am working on it, I would like to have a build process to distribute closh as a single library, which should solve most of installation troubles: https://github.com/dundalek/closh/issues/42

**Comment by mauricioszabo** [comment]
Can we add a submodule instead, so we'll be able to build `closh`? Probably, cloning a project from `master` branch and trying to build it locally, just to have an error would prevent more people from trying to help...

**Comment by dundalek** [comment]
Lumo is being pulled as an npm dependency now so this no longer applies.
