### ISSUE TITLE
Explore running with clj tool

### ISSUE THREAD

**Issue by dundalek** [dundalek/closh#65]
It should be possible to make closh run via the `clj` tool with `cljs.main` and node as eval target.

**Comment by dundalek** [comment]
Done in the dev branch. The limitation is that `clj` uses `rlwrap` for the readline functionality. Therefore the way to move forward is to utilize `rebel-readline`.

**Comment by arichiardi** [comment]
Pitching in -sorry out of context I know- for one thing only, you can use `clojure`, which is the script that does not use any `rlwrap`ing. Basically `rebel-readline` suggests to do the same in order to avoid conflicts.

**Comment by dundalek** [comment]
Yeah exactly, that is the plan. Stay tuned :wink:
