### ISSUE TITLE
[BUG] Multiline commands are not supported

### ISSUE THREAD

**Issue by NightMachinery** [dundalek/closh#67]
Just paste this snippet and you'll see:
```
(require-macros '[closh.core :refer [sh-str]])

(defn closh-prompt []
  (sh-str fish -c fish_prompt))
```
When I make it into one-line commands, the error is gone:
```
(require-macros '[closh.core :refer [sh-str]])

(defn closh-prompt []  (sh-str fish -c fish_prompt))
```

**Comment by dundalek** [comment]
Yeah, multiline input is not yet supported. See more in https://github.com/dundalek/closh/issues/17. I am closing this issue as duplicate.
