### ISSUE TITLE
[QUESTION] How to use conda?

### ISSUE THREAD

**Issue by NightMachinery** [dundalek/closh#69]
[Conda](https://anaconda.org/) uses a .sh script to start itself up, and running that script via `source-shell` does no good.

```
 $ conda activate

CommandNotFoundError: Your shell has not been properly configured to use 'conda activate'.
If your shell is Bash or a Bourne variant, enable conda for the current user with

    $ echo ". /Users/evar/anaconda/etc/profile.d/conda.sh" >> ~/.bash_profile

or, for all users, enable conda with

    $ sudo ln -s /Users/evar/anaconda/etc/profile.d/conda.sh /etc/profile.d/conda.sh

The options above will permanently enable the 'conda' command, but they do NOT
put conda's base (root) environment on PATH.  To do so, run

    $ conda activate

in your terminal, or to put the base environment on PATH permanently, run

    $ echo "conda activate" >> ~/.bash_profile

Previous to conda 4.4, the recommended way to activate conda was to modify PATH in
your ~/.bash_profile file.  You should manually remove the line that looks like

    export PATH="/Users/evar/anaconda/bin:$PATH"

^^^ The above line should NO LONGER be in your ~/.bash_profile file! ^^^
```

**Comment by dundalek** [comment]
I am not familiar with conda, but from the docs you posted it seems that the result of the `conda activate` is the thing that needs to be sourced. So this might do the trick:

```clojure
(source-shell (sh-str conda activate))
```

**Comment by NightMachinery** [comment]
Unfortunately it doesn't work, it uses custom bash functions it seems ...
It'd be good to add automatic bash-to-closh script conversion to the
roadmap?

**Comment by dundalek** [comment]
I see, I overlooked some details. Maybe try:
```clojure
(source-shell "bash" "/Users/evar/anaconda/etc/profile.d/conda.sh")
(source-shell "conda activate")
```

**Comment by dundalek** [comment]
@NightMachinary Were you able to run conda with those last commands?

**Comment by NightMachinery** [comment]
No, it returns errors:

**Comment by dundalek** [comment]
Could you provide the error output?

**Comment by NightMachinery** [comment]
@dundalek Oh, I had included an image of the error but it was lost during the mail to github conversion it seems. Here you go:
![image](https://user-images.githubusercontent.com/36224762/38779475-34d200e0-40de-11e8-83a9-d64995138b5e.png)

**Comment by dundalek** [comment]
@NightMachinary I just tried conda in a VM, and I think I got it now:
```
(source-shell ". ~/anaconda/etc/profile.d/conda.sh; conda activate")
```
Thanks for your patience.

**Comment by NightMachinery** [comment]
Thanks! This seems to work properly.

**Comment by dundalek** [comment]
Cool!
