### ISSUE TITLE
Terminal colours

### ISSUE THREAD

**Issue by lenw** [dundalek/closh#7]
Is there a way to get terminal colours ? Would that involve some sort of tty emulation ?

**Comment by willghatch** [comment]
If you mean colors when using `ls` and other commands, you get that by adding flags, eg. `ls --color=auto`.  Often operating systems will ship with a default `.bashrc` that includes something like `alias ls="ls --color=auto"`.

**Comment by dundalek** [comment]
Exactly as @willghatch said.
@lenw Do you get colors when you run `ls --color=auto`? If not which terminal are you using?

**Comment by dundalek** [comment]
Aliases are implemented now, so you can put following into your `~/.closhrc`:
```clj
(defalias ls "ls --color=auto")
```

Which gives you output like this:
![image](https://user-images.githubusercontent.com/755611/38833233-79594468-41b4-11e8-8fa8-01dffa305e69.png)

**Comment by lenw** [comment]
Thanks :+1:
