### ISSUE TITLE
Tab-completion errors out on certain input

### ISSUE THREAD

**Issue by dundalek** [dundalek/closh#78]
When typing out `(slurp ` (note there is a trailing space at the end) and hitting tab triggers completion error:

```
DEBUG: tab completion error %j
(node:28243) [DEP0028] DeprecationWarning: util.debug is deprecated. Use console.error instead.
```

Kudos to @TGThorax.

**Comment by jeroenvandijk** [comment]
I cannot reproduce this issue in the jar version

**Comment by dundalek** [comment]
Nor can I reproduce it in the node version, might have gone away with a lumo update or something. Thanks for digging through these :+1:
