### ISSUE TITLE
Logo Design

### ISSUE THREAD

**Issue by batarian71** [dundalek/closh#79]
Hi, Can I design a minimalist logo for Closh? Also, I can design something you want. What do you think?

**Comment by dundalek** [comment]
Hi, that would be neat and appreciated!

For starters I imagine a sea shell stylized with blue and green (like clojure or clojurescript logo) might look cool. But I would be happy to consider anything if you have already something in mind.

**Comment by batarian71** [comment]
There are several different options. Which do you like?

![closh](https://user-images.githubusercontent.com/36008612/40682027-72dfc84a-6393-11e8-886d-4c9e77573073.jpg)

**Comment by dundalek** [comment]
Thanks, I think the circle looks kinda generic, I would maybe try to drop it.

I sketched out some variants that I think might look cool:

![img_20180530_114354](https://user-images.githubusercontent.com/755611/40713313-2df3ea5c-63ef-11e8-83e4-17bd2413ea41.jpg)

**Comment by batarian71** [comment]
I designed it the way you want. I also added my own design. Which do you like?

![closh](https://user-images.githubusercontent.com/36008612/40755925-525df9ba-6489-11e8-8ac6-12708517df3e.jpg)

**Comment by dundalek** [comment]
Cool, I actually like yours at the bottom the most.

I think there might be still some room for simplification. It feels slightly noisy with so many lines. But I am not sure, maybe it's just a feeling.

I am quite happy with this iteration.

**Comment by batarian71** [comment]
I customized the logo. Which one do you prefer ? 

![closh 1](https://user-images.githubusercontent.com/36008612/40806000-c8444e8c-6528-11e8-9671-562cf7ad4d72.jpg)

**Comment by dundalek** [comment]
Hmm, I think I like the previous version better.

**Comment by batarian71** [comment]
I will send you the logonun files you like as pr.

**Comment by batarian71** [comment]
I sent a pr. https://github.com/dundalek/closh/pull/80 could you check it?

**Comment by dundalek** [comment]
PR with the logo merged in.
