### ISSUE TITLE
installing closh failes

### ISSUE THREAD

**Issue by nivpgir** [dundalek/closh#82]
installing closh fails.
i've traced it down to the sqlite3 dep failing, with this error:
https://github.com/Galooshi/import-js/issues/497

the fix seems to be to upgrade to sqlite3 v4, I don't know how complicated that will be for you, 
but in either way, is there a workaround to this? I would like to start trying closh for the last few hours but couldn't pass the installation phase.

**Comment by dundalek** [comment]
Could you try switching to node v9 and reinstalling closh? A convenient way to switch node versions is [nvm](https://github.com/creationix/nvm).

**Comment by nivpgir** [comment]
yeah, OK, that works...

should I have seen that that's the version I should use?

**Comment by dundalek** [comment]
It is in the readme with install instructions, but maybe it could be improved to make it more noticable?

**Comment by nivpgir** [comment]
maybe add a dependency section?
this would be good just for the sake of being noob friendly.

either way you can probably close this issue, no?

**Comment by dundalek** [comment]
I added a version check to the install script now, so it should be more obvious for the people in the future.
