### ISSUE TITLE
include nrepl server + middleware

### ISSUE THREAD

**Issue by hoebat** [dundalek/closh#88]
as per #66

**Comment by jeroenvandijk** [comment]
I think this would make development on `closh` easier as well. You could fix something and instantly retry instead of the `boot uberjar` cycle.

**Comment by dundalek** [comment]
I need to dig more into nrepl but I suspect this might be able to work just by adding the server startup code into `.closhrc`. However, it might be likely worth to make this as a built-in.

**Comment by dundalek** [comment]
@zcaudate Initial support is now included in master, details can be found in the [cookbook](https://github.com/dundalek/closh/blob/master/doc/cookbook.md#running-nrepl-server).

**Comment by hoebat** [comment]
@dundalek: ah awesome. this is amazing.
