### ISSUE TITLE
Warning for closh-prompt being overwritten

### ISSUE THREAD

**Issue by jeroenvandijk** [dundalek/closh#91]
Tiny issue (most likely), closh-prompt seems to be overwritten somewhere (huray for the jar version btw!)

<details>
  <summary>
    <p>
    WARNING: closh-prompt already refers to:     #'clojure.core/closh-prompt in namespace: user, being replaced by: #'user/closh-prompt
    </p>
    </summary>
    <p>
    
    ➜  bin git clone https://github.com/dundalek/closh.git
    Cloning into 'closh'...
    remote: Enumerating objects: 89, done.
    remote: Counting objects: 100% (89/89), done.
    remote: Compressing objects: 100% (32/32), done.
    remote: Total 2320 (delta 46), reused 81 (delta 42), pack-reused 2231
    Receiving objects: 100% (2320/2320), 1.35 MiB | 579.00 KiB/s, done.
    Resolving deltas: 100% (1259/1259), done.
    ➜  bin cd closh
    ➜  closh git:(master) boo
    ➜  closh git:(master) boot uberjar
    SLF4J: Failed to load class "org.slf4j.impl.StaticLoggerBinder".
    SLF4J: Defaulting to no-operation (NOP) logger implementation
    SLF4J: See http://www.slf4j.org/codes.html#StaticLoggerBinder for further details.
    Compiling 1/22 clojure.tools.reader...
    Compiling 2/22 clojure.tools.reader.default-data-readers...
    Compiling 3/22 clojure.tools.reader.edn...
    Compiling 4/22 clojure.tools.reader.impl.commons...
    Compiling 5/22 clojure.tools.reader.impl.errors...
    Compiling 6/22 clojure.tools.reader.impl.inspect...
    Compiling 7/22 clojure.tools.reader.impl.utils...
    Compiling 8/22 clojure.tools.reader.reader-types...
    Compiling 9/22 closh.zero.builtin...
    Compiling 10/22 closh.zero.compiler...
    Compiling 11/22 closh.zero.core...
    Compiling 12/22 closh.zero.env...
    Compiling 13/22 closh.zero.frontend.main...
    Compiling 14/22 closh.zero.frontend.rebel...
    Compiling 15/22 closh.zero.macros...
    Compiling 16/22 closh.zero.parser...
    Compiling 17/22 closh.zero.pipeline...
    Compiling 18/22 closh.zero.platform.io...
    Compiling 19/22 closh.zero.platform.process...
    Compiling 20/22 closh.zero.reader...
    Compiling 21/22 closh.zero.service.completion...
    Compiling 22/22 closh.zero.util...
    Adding uberjar entries...
    Writing project.jar...
    Sifting output files...
    Writing target dir(s)...
    ➜  closh git:(master) java -jar boot.properties
    ➜  closh git:(master) java -jar target/project.jar
    WARNING: closh-prompt already refers to: #'clojure.core/closh-prompt in namespace: user, being replaced by: #'user/closh-prompt
    $
</details>

**Comment by dundalek** [comment]
This warning should not appear anymore since the given var is declared as dynamic. Can you make sure to fetch the latest master and rebuild the uberjar? But it is totally possible I missed something.

**Comment by jeroenvandijk** [comment]
I did it in a clean directory, so unless there is system-wide caching (which I'm unaware of), it should be ok. I'll have a look somewhere today to see if I can fix it

**Comment by dundalek** [comment]
Aha, I think I know what the issue is now. Try dropping the `(ns user)` from `.closhrc`. There was a bug before which caused trouble without `ns` form, but now the config should be loaded in `user` ns by default.

**Comment by jeroenvandijk** [comment]
Ah good memory! I forgot about my `~/.closhrc`. That fixed it

**Comment by dundalek** [comment]
Sweet!
