### ISSUE TITLE
Usage: connecting via ssh doesn't work

### ISSUE THREAD

**Issue by jeroenvandijk** [dundalek/closh#97]
(with uberjar)

I just tried the `ssh` command to get into an ec2 instance. This process hangs, no errors, whereas the same command works fine in a bash shell.

```
$ ssh ec2-user@ec2-1-2-3-4.compute-1.amazonaws.com
```

I'm guessing this is an advanced piping operation?

**Comment by jeroenvandijk** [comment]
I'm guessing this is related to this?

closh
```
$ git clone git@github.com:dundalek/closh.git
Cloning into 'closh'...
```

bash
```
➜  git clone git@github.com:dundalek/closh.git
Cloning into 'closh'...
remote: Enumerating objects: 89, done.
remote: Counting objects: 100% (89/89), done.
remote: Compressing objects: 100% (29/29), done.
remote: Total 2320 (delta 47), reused 77 (delta 45), pack-reused 2231
Receiving objects: 100% (2320/2320), 1.35 MiB | 598.00 KiB/s, done.
Resolving deltas: 100% (1260/1260), done.
```

**Comment by dundalek** [comment]
I see, there are some kinks in output redirection, will look into this. This will likely result in broken vim, tmux, mc and other TUI applications.

In general for trying out the interactive usage I would recommend the node version, which I run as my primary shell and these kinds of things works with it.

**Comment by jeroenvandijk** [comment]
Awesome, I can confirm this works now!
